<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>colcon_rclgd</name>
  <version>2.1.0</version>
  <description>colcon build extension for rclgd (Godot Engine) packages</description>
  <maintainer email="miguelozubas@gmail.com">ozuba</maintainer>
  <license>MIT</license>

  <url type="repository">https://github.com/Ozuba/rclgd</url>
  <url type="bugtracker">https://github.com/Ozuba/rclgd/issues</url>
  <url type="website">https://rclgd.readthedocs.io/</url>

  <exec_depend>python3-colcon-common-extensions</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
