import os
import shutil
import stat
from pathlib import Path
from colcon_core.task import TaskExtensionPoint, run
from colcon_core.environment import create_environment_hooks, create_environment_scripts
from colcon_core.shell import create_environment_hook
from colcon_core.plugin_system import satisfies_version


class RclgdBuildTask(TaskExtensionPoint):
    def __init__(self):
        super().__init__()
        satisfies_version(TaskExtensionPoint.EXTENSION_POINT_VERSION, '^1.0')

    async def build(self, *, additional_hooks=None):
        pkg = self.context.pkg
        args = self.context.args
        additional_hooks = [] if additional_hooks is None else additional_hooks

        # Standard ROS 2 install structure
        package_install_base = Path(args.install_base)
        install_share = package_install_base / 'share' / pkg.name
        install_lib = package_install_base / 'lib' / pkg.name

        # 1. Synchronize Project Files
        if args.symlink_install:
            self._create_symlink(pkg.path, install_share)
        else:
            if install_share.exists():
                shutil.rmtree(install_share)
            shutil.copytree(pkg.path, install_share)

        # 2. Deploy Ament Index Markers
        self._deploy_markers(package_install_base, pkg.name, Path(pkg.path).resolve())

        # 3. Create Godot Launcher Shim
        self._create_shim(install_lib, pkg.name)

        # 4. Headless import of Godot assets
        await self._import_assets(install_share, pkg.name)

        # 5. Generate Shell Sourcing Files
        # First, create the specific ROS hook for this package
        additional_hooks.extend(
            create_environment_hook(
                'ament_prefix_path', package_install_base,
                pkg.name, 'AMENT_PREFIX_PATH', '', mode='prepend'
            )
        )

        # Gather default hooks (PATH, etc.)
        default_hooks = create_environment_hooks(args.install_base, pkg.name)

        # TRIGGER: This creates package.sh, package.bash, package.zsh, etc.
        create_environment_scripts(
            pkg, args, default_hooks=default_hooks, additional_hooks=additional_hooks
        )

        return 0

    def _deploy_markers(self, prefix, pkg_name, source_path):
        """Register the package with ament and record where its editable
        source lives (consumed by `ros2 rclgd editor` / `ros2 rclgd list`)."""
        index = prefix / 'share' / 'ament_index' / 'resource_index'
        for resource_type, content in (
                ('packages', ''),
                ('rclgd_project', str(source_path))):
            marker_dir = index / resource_type
            marker_dir.mkdir(parents=True, exist_ok=True)
            (marker_dir / pkg_name).write_text(content)

    def _create_shim(self, lib_dir, pkg_name):
        # The shim only locates the rclgd launcher (which resolves the actual
        # Godot binary) — pure bash, no `ros2 pkg prefix` python round-trips.
        #
        # ROS args handling: Godot only exposes arguments after a `--`
        # separator to scripts (OS.get_cmdline_user_args, read by the ROS
        # autoload). Users write the standard ROS invocation
        #   ros2 run pkg pkg --ros-args -p x:=y -r __ns:=/robot1
        # so the shim inserts the `--` in front of `--ros-args` itself. An
        # explicit `--` from the user disables the rewrite.
        lib_dir.mkdir(parents=True, exist_ok=True)
        shim_path = lib_dir / pkg_name
        content = f"""#!/usr/bin/env bash
# Generated by colcon_rclgd: runs the '{pkg_name}' Godot project.
SELF="$(readlink -f "${{BASH_SOURCE[0]}}")"
PREFIX="$(cd "$(dirname "$SELF")/../.." && pwd)"
LAUNCHER=""
IFS=':' read -ra _PREFIXES <<< "$PREFIX:${{AMENT_PREFIX_PATH:-}}"
for _p in "${{_PREFIXES[@]}}"; do
    if [ -x "$_p/lib/rclgd/godot" ]; then
        LAUNCHER="$_p/lib/rclgd/godot"
        break
    fi
done
if [ -z "$LAUNCHER" ]; then
    echo "{pkg_name}: rclgd not found on AMENT_PREFIX_PATH. Did you source your workspace?" >&2
    exit 2
fi

# Split args: everything from --ros-args onward goes after Godot's `--`
# separator so GDScript sees it via OS.get_cmdline_user_args(). Skipped if
# the user already passed `--` themselves.
GODOT_ARGS=()
ROS_ARGS=()
IN_ROS=0
HAS_SEP=0
for _a in "$@"; do
    [ "$_a" = "--" ] && HAS_SEP=1
done
for _a in "$@"; do
    if [ $HAS_SEP -eq 0 ] && {{ [ $IN_ROS -eq 1 ] || [ "$_a" = "--ros-args" ]; }}; then
        IN_ROS=1
        ROS_ARGS+=("$_a")
    else
        GODOT_ARGS+=("$_a")
    fi
done
if [ ${{#ROS_ARGS[@]}} -gt 0 ]; then
    exec "$LAUNCHER" --path "$PREFIX/share/{pkg_name}" "${{GODOT_ARGS[@]}}" -- "${{ROS_ARGS[@]}}"
fi
exec "$LAUNCHER" --path "$PREFIX/share/{pkg_name}" "${{GODOT_ARGS[@]}}"
"""
        shim_path.write_text(content)
        os.chmod(shim_path, os.stat(shim_path).st_mode | stat.S_IEXEC)

    def _create_symlink(self, target, link):
        if os.path.islink(link) or os.path.exists(link):
            os.remove(link) if os.path.islink(link) else shutil.rmtree(link)
        os.makedirs(link.parent, exist_ok=True)
        os.symlink(target, link)

    async def _import_assets(self, project_path, pkg_name):
        """Headless import of Godot assets into the install directory."""
        launcher = self._find_rclgd_launcher()
        if launcher is None:
            print(f"[{pkg_name}] Warning: rclgd launcher not found on "
                  "AMENT_PREFIX_PATH. Skipping resource import.")
            return

        # --editor --headless --import is the standard way to trigger the
        # initial import and shader compilation in Godot 4. The launcher exits
        # non-zero (with a hint) if no Godot binary is provisioned yet; never
        # download from inside a build.
        cmd = [
            str(launcher),
            '--editor',
            '--headless',
            '--import',
            '--path', str(project_path),
        ]

        try:
            completed = await run(self.context, cmd, cwd=str(project_path))
            if completed.returncode != 0:
                if (Path(project_path) / '.godot').is_dir():
                    # Assets were produced; the nonzero exit is Godot 4.7's
                    # crash-at-shutdown on first import (upstream engine bug).
                    print(f"[{pkg_name}] Note: Godot exited with "
                          f"{completed.returncode} after importing (known "
                          "Godot 4.7 first-import bug; assets were imported).")
                else:
                    print(f"[{pkg_name}] Warning: asset import failed "
                          f"(exit {completed.returncode}). If no Godot binary "
                          "is installed, rebuild rclgd (the engine is "
                          "installed by its build).")
        except Exception as e:
            print(f"[{pkg_name}] Resource import encountered an error: {e}")

    def _find_rclgd_launcher(self):
        for prefix in os.environ.get('AMENT_PREFIX_PATH', '').split(os.pathsep):
            if not prefix:
                continue
            candidate = Path(prefix) / 'lib' / 'rclgd' / 'godot'
            if candidate.is_file() and os.access(candidate, os.X_OK):
                return candidate
        return None
